name: Build Shaka Player

description: A reusable action to build Shaka Player.

runs:
  using: composite
  steps:
    - name: Build
      shell: bash
      run: |
        cd src/
        echo "::group::Building Shaka Player"
        build/build.py
        echo "::endgroup::"
