name: Test Shaka Player

# TODO: description

# TODO: use "--random" maybe?
# TODO: use "--external" maybe?

inputs:
  browser:
    description: The browser to run the test on.
    required: true

# TODO: try "--use-xvfb", to see if it fixes some of the linux failures
# TODO: try non-headless chrome/firefox on mac? see if that makes everything
# better?

runs:
  using: composite # TODO: what does this mean?
  steps:
    - name: Test
      shell: bash
      run: |
        cd src/
        echo "::group::Running tests"
        build/test.py --browsers ${{ inputs.browser }} \
            --use-xvfb --drm --reporter spec
        echo "::endgroup::"