name: Test Shaka Player

# TODO: description

# TODO: use "--random" maybe?
# TODO: use "--external" maybe?

inputs:
  browser:
    description: The browser to run the test on.
    required: true
  extra_flags:
    description: Any extra flags to pass in to the test.
    required: false

# TODO: try non-headless chrome/firefox on mac? see if that makes everything
# better?
# TODO: I'm testing this out with "--drm" disabled

runs:
  using: composite # TODO: what does this mean?
  steps:
    - name: Test
      shell: bash
      run: |
        cd src/
        echo "::group::Running tests"
        build/test.py --browsers ${{ inputs.browser }} --reporter spec \
            ${{ inputs.extra_flags }}
        echo "::endgroup::"