name: Test Shaka Player

# TODO: description

# TODO: use "--random" maybe?
# TODO: use "--external" maybe?

inputs:
  browser:
    description: The browser to run the test on.
    required: true

runs:
  using: composite # TODO: what does this mean?
  steps:
    - name: Test
      shell: bash
      run: |
        cd src/
        echo "::group::Running tests"
        build/test.py --browsers ${{ inputs.browser }} --drm --reporter dots
        echo "::endgroup::"