name: Test Shaka Player

description: A reusable action to run tests on Shaka Player.

inputs:
  browser:
    description: The browser to run the test on.
    required: true
  extra_flags:
    description: Any extra flags to pass in to the test.
    required: false

runs:
  using: composite
  steps:
    - name: Test
      shell: bash
      run: |
        cd src/
        echo "::group::Running tests"
        build/test.py --browsers ${{ inputs.browser }} --reporter spec --drm \
            ${{ inputs.extra_flags }}
        echo "::endgroup::"
